"""Shadow-only reusable strategy packaging and risk invariants."""

from trading_codex.shadow.risk_invariants import (
    DrawdownKillSwitchConfig,
    LiquidityCheckConfig,
    PositionCapConfig,
    RegimeGuardrailConfig,
    RiskInvariantConfig,
    RiskInvariantReport,
    TurnoverCapConfig,
    evaluate_risk_invariants,
)
from trading_codex.shadow.stage2_candidates import (
    PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_DEFENSIVE_SYMBOL,
    PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_MOMENTUM_LOOKBACK,
    PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_RISK_SYMBOLS,
    PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_REBALANCE,
    PRIMARY_LIVE_CANDIDATE_V1_ID,
    PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_PRESET,
    PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_STATE_KEY,
    PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_STRATEGY,
    PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_DEFAULT_TARGET_VOL,
    PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_DEFAULT_VOL_LOOKBACK,
    PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_ID,
    ControlPlaneStrategyMapping,
    ShadowStrategyRuntimeConfig,
    build_shadow_template_for_strategy,
    primary_live_candidate_v1_runtime_mapping,
    primary_live_candidate_v1_vol_managed_shadow_config,
)
from trading_codex.shadow.template import (
    ShadowStrategyOutputs,
    ShadowStrategyTemplate,
    build_local_shadow_template,
    build_primary_live_candidate_v1_vol_managed_shadow_template,
)

__all__ = [
    "DrawdownKillSwitchConfig",
    "LiquidityCheckConfig",
    "PositionCapConfig",
    "PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_DEFENSIVE_SYMBOL",
    "PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_MOMENTUM_LOOKBACK",
    "PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_RISK_SYMBOLS",
    "PRIMARY_LIVE_CANDIDATE_V1_DEFAULT_REBALANCE",
    "PRIMARY_LIVE_CANDIDATE_V1_ID",
    "PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_PRESET",
    "PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_STATE_KEY",
    "PRIMARY_LIVE_CANDIDATE_V1_RUNTIME_STRATEGY",
    "PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_DEFAULT_TARGET_VOL",
    "PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_DEFAULT_VOL_LOOKBACK",
    "PRIMARY_LIVE_CANDIDATE_V1_VOL_MANAGED_ID",
    "RegimeGuardrailConfig",
    "RiskInvariantConfig",
    "RiskInvariantReport",
    "TurnoverCapConfig",
    "ControlPlaneStrategyMapping",
    "ShadowStrategyRuntimeConfig",
    "ShadowStrategyOutputs",
    "ShadowStrategyTemplate",
    "build_shadow_template_for_strategy",
    "build_local_shadow_template",
    "build_primary_live_candidate_v1_vol_managed_shadow_template",
    "primary_live_candidate_v1_runtime_mapping",
    "primary_live_candidate_v1_vol_managed_shadow_config",
    "evaluate_risk_invariants",
]
